---@type SP_RaceConfigVars
RaceConfigVars = {}

local RACECONFIG_PATH = "DevouringAndDigesting\\RaceConfig.json"

---races that are considered creatures for config
---@type table<string,boolean>
SINGLE_GENDER_CREATURE = {
    ["Humanoid"] = false,
    ["Human"] = false,
    ["Elf"] = false,
    ["HighElf"] = false,
    ["WoodElf"] = false,
    ["Drow"] = false,
    ["LolthDrow"] = false,
    ["SeldarineDrow"] = false,
    ["Dwarf"] = false,
    ["HillDwarf"] = false,
    ["MountainDwarf"] = false,
    ["Duergar"] = false,
    ["HalfElf"] = false,
    ["HighHalfElf"] = false,
    ["WoodHalfElf"] = false,
    ["HalfDrow"] = false,
    ["Gnome"] = false,
    ["RockGnome"] = false,
    ["DeepGnome"] = false,
    ["ForestGnome"] = false,
    ["Halfling"] = false,
    ["LightfootHalfling"] = false,
    ["StoutHalfling"] = false,
    ["Tiefling"] = false,
    ["AsmodeusTiefling"] = false,
    ["MephistophelesTiefling"] = false,
    ["ZarielTiefling"] = false,
    ["Githyanki"] = false,
    ["Goblin"] = false,
    ["Hobgoblin"] = false,
    ["Bugbear"] = false,
    ["Gnoll"] = true,
    ["Gnoll Flind"] = true,
    ["Werewolf"] = false,
    ["Kuotoa"] = true,
    ["Undead"] = false,
    ["Skeleton"] = true,
    ["Monstrosity"] = true,
    ["Ettercap"] = true,
    ["Harpy"] = false,
    ["PhaseSpider"] = true,
    ["Giant"] = false,
    ["Ogre"] = false,
    ["Ooze"] = true,
    ["Aberration"] = true,
    ["Beholder"] = true,
    ["Mindflayer"] = true,
    ["Celestial"] = false,
    ["Elemental"] = true,
    ["Elemental_Mud"] = true,
    ["Elemental_Lava"] = true,
    ["Mephit"] = true,
    ["Azer"] = false,
    ["Fey"] = false,
    ["Redcap"] = false,
    ["Fiend"] = false,
    ["Devil"] = false,
    ["Demon"] = false,
    ["Construct"] = true,
    ["ScryingEye"] = true,
    ["Automaton"] = true,
    ["AdamantineGolem"] = true,
    ["AnimatedArmor"] = true,
    ["Plant"] = true,
    ["Myconid"] = true,
    ["Bulette"] = true,
    ["Hook Horror"] = true,
    ["Beast"] = true,
    ["Spider"] = true,
    ["Dragon"] = true,
    ["Critter"] = true,
    ["Rat"] = true,
    ["Bird"] = true,
    ["Frog"] = true,
    ["Crab"] = true,
    ["EMPTY"] = false,
    ["UndeadHighElfHidden"] = false,
    ["UndeadHighElfRevealed"] = false,
    ["MagicalSpecter"] = false,
    ["Zombie"] = true,
    ["Hellsboar"] = true,
    ["Imp"] = true,
    ["Cambion"] = false,
    ["Hag"] = false,
    ["Badger"] = true,
    ["Merregon"] = false,
    ["Wolf"] = true,
    ["Raven"] = true,
    ["Bear"] = true,
    ["Boar"] = true,
    ["Hyena"] = true,
    ["Dragonborn"] = false,
    ["BlackDragonborn"] = false,
    ["BlueDragonborn"] = false,
    ["BrassDragonborn"] = false,
    ["BronzeDragonborn"] = false,
    ["CopperDragonborn"] = false,
    ["GoldDragonborn"] = false,
    ["GreenDragonborn"] = false,
    ["RedDragonborn"] = false,
    ["SilverDragonborn"] = false,
    ["WhiteDragonborn"] = false,
    ["HalfOrc"] = false,
    ["Kobold"] = true,
    ["DarkJusticiar"] = false,
    ["Blight"] = true,
    ["Meazel"] = true,
    ["Brewer"] = true,
    ["ShadarKai"] = false,
    ["Ghost"] = false,
    ["CrawlingClaw"] = true,
    ["TollCollector"] = true,
    ["Gremishka"] = true,
    ["ApostleOfMyrkul"] = true,
    ["ShadowMastiff"] = true,
    ["Phasm"] = true,
    ["FleshGolem"] = true,
    ["Meenlock"] = true,
    ["Shadow"] = true,
    ["Wraith"] = true,
    ["Cloaker"] = true,
    ["FlyingGhoul"] = true,
    ["GiantEagle"] = true,
    ["Ghoul"] = true,
    ["UndeadFace"] = true,
    ["CoinHalberd"] = true,
    ["Surgeon"] = false,
    ["OliverFriend"] = false,
    ["Mummy"] = false,
    ["Mummy Lord"] = false,
    ["Tressym"] = true,
    ["SkeletalDragon"] = true,
    ["Hollyphant"] = true,
    ["Steelwatcher"] = true,
    ["Shambling Mound"] = true,
    ["Alioramus"] = true,
    ["Butler"] = false,
    ["DeathKnight"] = false,
    ["Ghast"] = true,
    ["Incubus"] = false,
    ["Succubus"] = false,
    ["Vampire"] = false,
    ["VampireSpawn"] = false,
    ["Vengeful Imp"] = true,
    ["Vengeful Boar"] = true,
    ["Vengeful Cambion"] = false,
    ["Raphaelian Merregon"] = false,
    ["Redcap Pirate"] = false,
    ["Blink Dog"] = true,
    ["Aasimar"] = false,
    ["Doppelganger"] = true,
    ["Bat"] = true,
    ["Displacer Beast"] = true,
}

---chance of a race being given pred passive
---@class SP_RaceConfigVars
DEFAULT_RACE_TABLE = {
    ["Humanoid"] = 1.0,
    ["Human"] = 1.0,
    ["Elf"] = 1.0,
    ["HighElf"] = 1.0,
    ["WoodElf"] = 1.0,
    ["Drow"] = 1.0,
    ["LolthDrow"] = 1.0,
    ["SeldarineDrow"] = 1.0,
    ["Dwarf"] = 1.0,
    ["HillDwarf"] = 1.0,
    ["MountainDwarf"] = 1.0,
    ["Duergar"] = 1.0,
    ["HalfElf"] = 1.0,
    ["HighHalfElf"] = 1.0,
    ["WoodHalfElf"] = 1.0,
    ["HalfDrow"] = 1.0,
    ["Gnome"] = 0.5,
    ["RockGnome"] = 0.5,
    ["DeepGnome"] = 0.5,
    ["ForestGnome"] = 0.5,
    ["Halfling"] = 0.5,
    ["LightfootHalfling"] = 0.5,
    ["StoutHalfling"] = 0.5,
    ["Tiefling"] = 1.0,
    ["AsmodeusTiefling"] = 1.0,
    ["MephistophelesTiefling"] = 1.0,
    ["ZarielTiefling"] = 1.0,
    ["Githyanki"] = 1.0,
    ["Goblin"] = 1.0,
    ["Hobgoblin"] = 2.0,
    ["Bugbear"] = 2.0,
    ["Gnoll"] = 2.0,
    ["Gnoll Flind"] = 2.0,
    ["Werewolf"] = 3.0,
    ["Kuotoa"] = 2.0,
    ["Undead"] = 1.0,
    ["Skeleton"] = 0.0,
    ["Monstrosity"] = 2.0,
    ["Ettercap"] = 2.0,
    ["Harpy"] = 2.0,
    ["PhaseSpider"] = 1.0,
    ["Giant"] = 4.0,
    ["Ogre"] = 4.0,
    ["Ooze"] = 3.0,
    ["Aberration"] = 2.0,
    ["Beholder"] = 2.0,
    ["Mindflayer"] = 0.0,
    ["Celestial"] = 1.0,
    ["Elemental"] = 0.5,
    ["Elemental_Mud"] = 0.5,
    ["Elemental_Lava"] = 0.5,
    ["Mephit"] = 0.25,
    ["Azer"] = 0.5,
    ["Fey"] = 2.0,
    ["Redcap"] = 1.0,
    ["Fiend"] = 2.0,
    ["Devil"] = 2.0,
    ["Demon"] = 3.0,
    ["Construct"] = 0.0,
    ["ScryingEye"] = 0.0,
    ["Automaton"] = 0.0,
    ["AdamantineGolem"] = 0.0,
    ["AnimatedArmor"] = 0.0,
    ["Plant"] = 0.0,
    ["Myconid"] = 0.5,
    ["Bulette"] = 3.0,
    ["Hook Horror"] = 2.0,
    ["Beast"] = 1.0,
    ["Spider"] = 1.0,
    ["Dragon"] = 100.0,
    ["Critter"] = 0.0,
    ["Rat"] = 0.0,
    ["Bird"] = 0.0,
    ["Frog"] = 0.0,
    ["Crab"] = 0.0,
    ["EMPTY"] = 0.0,
    ["UndeadHighElfHidden"] = 2.0,
    ["UndeadHighElfRevealed"] = 2.0,
    ["MagicalSpecter"] = 0.0,
    ["Zombie"] = 0.5,
    ["Hellsboar"] = 1.0,
    ["Imp"] = 0.0,
    ["Cambion"] = 4.0,
    ["Hag"] = 3.0,
    ["Badger"] = 1.0,
    ["Merregon"] = 2.0,
    ["Wolf"] = 2.0,
    ["Raven"] = 0.0,
    ["Bear"] = 2.0,
    ["Boar"] = 0.5,
    ["Hyena"] = 0.5,
    ["Dragonborn"] = 1.0,
    ["BlackDragonborn"] = 1.0,
    ["BlueDragonborn"] = 1.0,
    ["BrassDragonborn"] = 1.0,
    ["BronzeDragonborn"] = 1.0,
    ["CopperDragonborn"] = 1.0,
    ["GoldDragonborn"] = 1.0,
    ["GreenDragonborn"] = 1.0,
    ["RedDragonborn"] = 1.0,
    ["SilverDragonborn"] = 1.0,
    ["WhiteDragonborn"] = 1.0,
    ["HalfOrc"] = 1.0,
    ["Kobold"] = 0.5,
    ["DarkJusticiar"] = 1.0,
    ["Blight"] = 0.0,
    ["Meazel"] = 0.0,
    ["Brewer"] = 100.0,
    ["ShadarKai"] = 1.0,
    ["Ghost"] = 0.0,
    ["CrawlingClaw"] = 0.0,
    ["TollCollector"] = 0.0,
    ["Gremishka"] = 0.0,
    ["ApostleOfMyrkul"] = 0.0,
    ["ShadowMastiff"] = 0.5,
    ["Phasm"] = 100.0,
    ["FleshGolem"] = 0.0,
    ["Meenlock"] = 0.5,
    ["Shadow"] = 0.0,
    ["Wraith"] = 0.0,
    ["Cloaker"] = 1.0,
    ["FlyingGhoul"] = 1.0,
    ["GiantEagle"] = 2.0,
    ["Ghoul"] = 0.5,
    ["UndeadFace"] = 0.0,
    ["CoinHalberd"] = 0.0,
    ["Surgeon"] = 0.0,
    ["OliverFriend"] = 0.0,
    ["Mummy"] = 0.0,
    ["Mummy Lord"] = 0.0,
    ["Tressym"] = 0.0,
    ["SkeletalDragon"] = 0.0,
    ["Hollyphant"] = 0.0,
    ["Steelwatcher"] = 0.0,
    ["Shambling Mound"] = 4.0,
    ["Alioramus"] = 2.0,
    ["Butler"] = 0.0,
    ["DeathKnight"] = 0.0,
    ["Ghast"] = 0.5,
    ["Incubus"] = 100.0,
    ["Succubus"] = 100.0,
    ["Vampire"] = 2.0,
    ["VampireSpawn"] = 2.0,
    ["Vengeful Imp"] = 0.0,
    ["Vengeful Boar"] = 0.5,
    ["Vengeful Cambion"] = 3.0,
    ["Raphaelian Merregon"] = 3.0,
    ["Redcap Pirate"] = 0.5,
    ["Blink Dog"] = 0.5,
    ["Aasimar"] = 1.0,
    ["Doppelganger"] = 1.0,
    ["Bat"] = 0.0,
    ["Displacer Beast"] = 2.0,
}

---these npcs will always become preds
---@type table<string, boolean>
PRED_NPC_TABLE = {
    ["S_GLO_Nightsong_6c55edb0-901b-4ba4-b9e8-3475a8392d9b"] = true,
    ["LOW_Slayer_Orin_ced6bfeb-8f6f-47d0-943f-77833f643318"] = true,
    ["S_GLO_Orin_bf24e0ec-a3a6-4905-bd2d-45dc8edf8101"] = true,
    ["Ooze_Jelly_Phasm_41a2b951-d2cf-48fe-bdd8-945fdec653b2"] = true,
}

function SP_SaveRaceWeightsConfig()
    local json = Ext.Json.Stringify(RaceWeightVars)
    Ext.IO.SaveFile(RACECONFIG_PATH, json)
    _P("Config saved: \"Script Extender\\" .. RACECONFIG_PATH .. "\".")
end

function SP_ResetRaceWeightsConfig()
    RaceWeightVars = SP_Deepcopy(DEFAULT_RACE_TABLE)
    _P("Default race weights loaded.")
end

function SP_ResetAndSaveRaceWeightsConfig()
    SP_ResetRaceWeightsConfig()
    SP_SaveRaceWeightsConfig()
end


function SP_LoadRaceWeightsConfigFromFile()
    local content = Ext.IO.LoadFile(RACECONFIG_PATH)
    if content == nil then
        _P("Race Weights Config not found. If this is your first time launching the game with this mod enabled, this is fine.")
        SP_ResetRaceWeightsConfig()
        SP_SaveRaceWeightsConfig()
        return
    end

    _P("Race Weights Config loaded: \"Script Extender\\" .. RACECONFIG_PATH .. "\".")

    RaceConfigVars = Ext.Json.Parse(content)

end
